# OpenAI 配置
openai:
  api_key: "your-openai-api-key"
  model: "gpt-3.5-turbo"
  api_base: "https://api.openai.com/v1"
  timeout: 30
  max_retries: 3
  temperature: 0.7
  max_tokens: 2000

# 通义千问配置
qwen:
  api_key: "your-qwen-api-key"
  model: "qwen-turbo"
  timeout: 30
  max_retries: 3
  temperature: 0.7
  max_tokens: 2000

# Anthropic Claude 配置
anthropic:
  api_key: "your-anthropic-api-key"
  model: "claude-3-opus-20240229"
  api_base: "https://api.anthropic.com/v1"
  api_version: "2023-06-01"
  timeout: 30
  max_retries: 3
  temperature: 0.7
  max_tokens: 2000 